### PR TITLE
feat: add tailwindCSS

### PR DESCRIPTION
**Pull request by LaichuLai**
feat: install tailwindCSS

        modified:   app/javascript/packs/application.js
        new file:   app/javascript/stylesheets/application.css
        modified:   app/views/layouts/application.html.erb
        modified:   package.json
        modified:   postcss.config.js
        new file:   tailwind.config.js
        modified:   yarn.lock

### CODE REVIEW

**Review by sethxd88 — APPROVED** [review]
謝謝9527！

**Review by Tsaijieming — APPROVED** [review]
tailwind is wet !

**Comment by ching227** [comment]
yaaa

**Review by Tsaijieming — COMMENTED** [review]
go

**Comment by ching227** [comment]
yaa

**Review by ching227 — COMMENTED** [review]
yaaa

**Comment by ching227** [comment]
剛剛試著按了一些其他地方哈哈哈

**Pull request merged**
